### ISSUE TITLE
AxonServer LEAK: ByteBuf.release() was not called before it's garbage-collected

### ISSUE THREAD

**Issue by ViliusS** [AxonIQ/axon-server-se#463] opened 2022-03-27 17:32 UTC
Our AxonServer SE 4.5.10 docker instance sometimes have an issue where it goes into a state which produces these errors and related warnings: 

```
2022-02-24 13:42:08.104 ERROR 1 --- [-worker-ELG-3-1] io.netty.util.ResourceLeakDetector       : LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
```

After a while it even changes to Out Of Heap Space errors. Sounds like a memory leak bug in AxonServer itself?

Full log attached. If anyone knows how to debug this or if more information is needed from our side, don't hesitate to ask.
[axon leak log.txt](https://github.com/AxonIQ/axon-server-se/files/8358140/axon.leak.log.txt)

**Comment by MGathier** [comment] 2022-03-28 13:00
Thanks for reporting this. We will investigate the issue. 
Could you start the docker instance with the environment option:
  JAVA_TOOL_OPTIONS="-XX:HeapDumpPath=/data -XX:+HeapDumpOnOutOfMemoryError"
This would create a memory dump in /data if the JVM runs out of heap space.

**Comment by ViliusS** [comment] 2022-03-29 06:01
Done.

For some reason that one liner in the logs is marked as an error, but it's probably OK?
```
Error 2022-03-29T05:58:29.394936679ZPicked up JAVA_TOOL_OPTIONS: -XX:HeapDumpPath=/data -XX:+HeapDumpOnOutOfMemoryError
Info 2022-03-29T05:58:35.112679109Z _ ____
Info 2022-03-29T05:58:35.112738717Z / \ __ _____ _ __ / ___| ___ _ ____ _____ _ __
Info 2022-03-29T05:58:35.112751740Z / _ \ \ \/ / _ \| '_ \\___ \ / _ \ '__\ \ / / _ \ '__|
Info 2022-03-29T05:58:35.112760599Z / ___ \ > < (_) | | | |___) | __/ | \ V / __/ |
Info 2022-03-29T05:58:35.112770205Z /_/ \_\/_/\_\___/|_| |_|____/ \___|_| \_/ \___|_|
Info 2022-03-29T05:58:35.112777852Z Standard Edition Powered by AxonIQ
Info 2022-03-29T05:58:35.112784808Z{}
Info 2022-03-29T05:58:35.112794213Zversion: 4.5.10
Info 2022-03-29T05:58:35.273894818Z2022-03-29 05:58:35.270 INFO 1 --- [ main] io.axoniq.axonserver.AxonServer : Starting AxonServer using Java 11.0.13 on axonserver-8879b449b-tkd86 with PID 1 (/app/classes started by root in /)
```

**Comment by ViliusS** [comment] 2022-04-04 06:22
It happened again. Attached new logs:
[axon-outofdirectmemory.zip](https://github.com/AxonIQ/axon-server-se/files/8407063/axon-outofdirectmemory.zip)

Looks like something is not clearing DirectMemory. Container memory usage increases day by day until Axon stops.
![axon-podmemory](https://user-images.githubusercontent.com/2323565/161483009-8b0692d5-1448-4f61-adf5-574a3438cc7e.png)

I'm still struggling to find a way to retrieve Heap dump data from our pod running distroless image :|

**Comment by MGathier** [comment] 2022-04-13 11:49
I have tried to reproduce this situation here, but so far no luck. I tried this by sending large commands, that would timeout, but that did not increase the used memory. Since the docker image is based on a distroless image it is hard to check inside the container, but there are a few things we can do. 
Can you start the container with the environment option:
MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=metrics,info,health,loggers,prometheus,env,heapdump,threaddump

this will expose 2 additional endpoints, /actuator/heapdump and /actuator/threaddump 
If you can invoke these 2 endpoints twice, for instance, one day apart, we can better investigate what is happening in Axon Server.

**Comment by ViliusS** [comment] 2022-04-14 14:47
Thanks, I have configured new options and will capture heap and threads daily. Will update the ticket in couple of days with the dumps.

I have also asked our developers to write a small java application which would reproduce the issue on our side. Will share the code if they achieve this.

**Comment by ViliusS** [comment] 2022-05-11 05:55
Just to let you know, not sure if that's because of our codebase changes or something else, but we don't see the issue anymore. I think we can close it at the moment and reopen if we see it again.

**Comment by MGathier** [comment] 2022-05-11 10:01
Closing this issue for now as it does not happens anymore.

**Closed by MGathier** 2022-05-11 10:01 UTC
